name: Build and Deploy
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # Copied from https://github.com/MarketingPipeline/Python-Selenium-Action/
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay undetected-chromedriver
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - uses: actions/cache@v3
        if: github.event_name != 'schedule'
        with:
          path: cache/bolaget*
          key: ${{ runner.os }}-bolaget-cache
      - uses: actions/cache@v3
        if: github.event_name == 'push'
        with:
          path: cache/untappd*
          key: ${{ runner.os }}-untappd-cache
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          rebar3-version: v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          rebar3 escriptize
          ./_build/default/bin/systap
          mkdir html
          mv index.html html/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cache
          path: cache

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html # The folder the action should deploy.
